name: Publish to Docker

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # define la imagen explícitamente en minúsculas
          images: |
            ghcr.io/${{ github.repository_owner }}/publish-packages-game
          tags: |
            type=sha,format=long
            # opcional: type=ref,event=branch

      - name: Show computed tags (debug)
        run: |
          echo "TAGS:"
          echo "${{ steps.meta.outputs.tags }}"
          echo "IMAGES:"
          echo "${{ steps.meta.outputs.images }}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

